# Use the official Golang image as the parent image
FROM golang:1.16.4

# Set the current working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Download the dependencies (this will skip installing them individually)
RUN go mod download

# Copy the rest of the application code to the container
COPY . .

# Build the application
RUN go build -o main .

# Expose port 8080 for the container
EXPOSE 8080

# Start the application
CMD ["./main"]
