# Use the official Golang image as the parent image
FROM golang:latest

# RUN mkdir -p /sticker
# Set the current working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY go.mod .
COPY go.sum .

# Download the dependencies (this will skip installing them individually)
RUN go mod download

# Copy the rest of the application code to the container
COPY . .

# Build the application
RUN go build -o main app/main.go

# Expose port 8080 for the container
EXPOSE 8080

# Start the application
CMD ["./main"]
