[[redirects]]
  from = "/config/config.yaml"
  to = "/config.yaml"

[[redirects]]
  from = "/config/*"
  to = "/config/:splat"


[build]
  command = "go build -o app/main app/main.go"
  publish = "app, app/config"
  functions = "app/functions"
