[[redirects]]
  from = "/config/config.json"
  to = "/config.json"

[[redirects]]
  from = "/config/*"
  to = "/config/:splat"

[build]
  command = "go build -o app/main app/main.go"
  publish = "app"
  environment = { APP_ENV = "production" }
